version: "3.7"
services:
  frontend:
    image: ${REGISTRY}/kartki:${IMAGE_TAG}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.frontend.rule=Host(`flashcard.pro`) || Host(`www.flashcard.pro`)
      - traefik.http.services.frontend.loadBalancer.server.port=80
      - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.flashcard.pro/(.*)$$
      - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}flashcard.pro/$${2}
      - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
      - traefik.http.routers.frontend.middlewares=frontend-redirect,secure-headers
      - traefik.http.routers.frontend.entryPoints=https
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certResolver=letsEncrypt
    networks:
      - traefik-public
      - default

networks:
    traefik-public:
        external: true
