version: "3.7"
services:
  kartki:
    image: ${REGISTRY:-localhost}/kartki-dev:cache
    build:
      context: docker/development/nginx
      cache_from:
        - ${REGISTRY:-localhost}/kartki-dev:cache
    depends_on:
      - kartki-node
    networks:
        - traefik-public
        - default
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.kartki.rule=Host(`localhost`)
        - traefik.http.routers.kartki.entryPoints=http

  kartki-node:
    image: ${REGISTRY:-localhost}/kartki-dev-node:cache
    build:
      context: docker/development/node
      cache_from:
        - ${REGISTRY:-localhost}/kartki-dev-node:cache
    ports:
      - "${FRONTEND_NODE_PORT:-3000}:3000"
    volumes:
      - .:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    tty: true

  kartki-node-cli:
    image: ${REGISTRY:-localhost}/kartki-dev-node-cli:cache
    build:
      context: docker/development/node
      cache_from:
        - ${REGISTRY:-localhost}/kartki-dev-node-cli:cache
    volumes:
      - .:/app

networks:
    traefik-public:
        external: true
